<div style="position: relative; left: -180px; top: 20px;background:#fff;">
<table>
<tr>
<td valign="center" width="80px">
<a target="_blank" href="http://www.tekstlab.uio.no/nota/NorAmDiaSyn/">
<img style='border-style: none' alt="Nordic dialect corpus" src="img/amerikanorsk.png" />
</a>
</td>
</tr>
</table>
</div>

<div style="position: relative; left: -220px; top: 32px">
<ul>
  <li><a target="_blank" href="http://www.tekstlab.uio.no/nota/NorAmDiaSyn/">Transcription guidelines, translation lists, etc</a></li>
<!--  <li><a target="_blank" href="http://www.tekstlab.uio.no/nota/amerikanorsk/kart.html">Recording locations</a></li> -->
  <li><a target="_blank" href="transcriptions/amerikanorsk">Transcriptions</a></li>
</ul>
</div>