<div style="position: relative; left: -180px; top: 20px;background:#fff;">
<table>
<tr>
<td valign="center" width="80px">
<a target="_blank" href="http://www.tekstlab.uio.no/nota/bigbrother/">
<img style='border-style: none' alt="Big Brother Corpus" src="http://www.tekstlab.uio.no/nota/img/bigbrother.jpg" />
</a>
</td>
</tr>
<tr>
<td valign="center" width="80px">
</td>
</tr>
</table>
</div>
<div style="position: relative; left: -220px; top: 32px">
<ul>
  <li><a target="_blank" href="transcriptions/bigbrother">Transcriptions</a></li>
  <li><a target="_blank" href="http://www.tekstlab.uio.no/nota/scandiasyn/help/">News: Search Interface Documentation</a></li>
</ul>
</div>