<br>
<br>

<h3>Bokmålskorpuset</h3>
Utviklet av Seksjon for leksikografi <br>
(Avdeling for Bokmål) ved Institutt for <br>
lingvistiske og nordiske studier, UiO; <br> 
sammen med
<a href='http://www.hf.uio.no/tekstlab/'>
  Tekstlaboratoriet
</a>.

<br>
<br>

<a href='http://www.hf.uio.no/tekstlab'>
  <img style='border-style: none' src='img/logo.png' />
</a> 

<br><br>

<a href='http://www.hf.uio.no/iln'>
  <img style='border-style: none' src='img/logo-uio.png' />
</a>
