<div style="position: relative; left: -180px; top: 20px;background:#fff;">
<table>
<tr>
<td style='border-width:2px;border-style:outset;background:#cde;' valign="center" width="200px">
<span style="font-family:gothic century;font-variant:small-caps;font-weight:bold;font-size:1.4em;cursor:pointer;" onclick="document.location='http://www.hf.uio.no/iln/om/organisasjon/tekstlab/prosjekter/ruija/ruija.html';">Ruija</span><br />
<span style="font-family:gothic century;font-variant:small-caps;font-weight:light;font-size:1.1em;">Et talespråkskorpus fra kvensk- og finskspråklige områder</span>
</td>
</tr>
</table>
<span style="font-family:gothic century;font-variant:small-caps;font-weight:light;font-size:1.1em;"><a target="_blank" href="http://omilia.uio.no/ruija/">Transkripsjoner (html)</a></span>
</div>

