<div style="position: relative; left: -180px; top: 20px;background:#fff;">
<table>
<tr>
<td style='border-width:1px;border-style:outset;background:#ffc;' valign="center" width="200px">
   <span style="font-family:gothic century;font-weight:bold;font-size:1.4em;cursor:pointer;" onclick="document.location='';">EngL2</span><br />
<span style="font-family:gothic century;font-variant:small-caps;font-weight:light;font-size:1.1em;">Norske elevers bruk av engelsk</span>
</td>
</tr>
</table>
<!-- <span style="font-family:gothic century;font-variant:small-caps;font-weight:light;font-size:1.1em;"><a target="_blank" href="http://omilia.uio.no/">Transkripsjoner (html)</a></span> -->
</div>

