<table>
  <tr>
    <td valign="top">
      <input type="hidden" name="meta_values_active::ENGL2author.active" value="y" />
      <input type="hidden" name="meta_mode_active" value="LIKE" />
      <script language="javascript">writeWidgetDoubleTable('tid','student code','hidden')</script>
    </td>
    <td valign="top">
     <script language="javascript">writeWidgetDoubleTable('language','first language','hidden')</script>
    </td>
    <td valign="top">
     <script language="javascript">writeWidgetDoubleTable('pronunciation','pronunciation','hidden')</script>
    </td>
  </tr>
</table>
<hr />
<table>
<table>
  <tr>
    <td valign="top">
      <script language="javascript">writeWidgetRadio('sex','sex', 'hidden')</script>
    </td>

    <td valign="top">
   <script language="javascript">writeWidgetDoubleTable('raised','raised', 'hidden')</script>
    </td>
    <td valign="top">
      <script language="javascript">writeWidgetDoubleTable('schoolstart','started school', 'hidden')</script>
    </td>

  </tr>
</table>