<br>
<br>
<h3>French Newspaper Corpus</h3>
<h4>Part 4 - Le Monde 1989 - 1990 and 1992 - 1993</h4>
<p>
Developed by <a href='http://www.hf.uio.no/tekstlab/'>The Text Laboratory</a>. 
</p>
<p>
<a href="http://www.hf.uio.no/tekstlab"><img style="border-style: none" src="http://omilia.uio.no/glossa/html/img/logo.png" /></a>
</p>
<p>
Contains texts from the <a href="http://www.ldc.upenn.edu/" target="_blank">Linguistic Data Consortium</a>
</p>
<p>
<a href="http://www.ldc.upenn.edu/"><img style="border-style: none" src="http://www.ldc.upenn.edu/Shared/Graphics/logo.gif" /></a>
</p>
<p>
and the <a href="http://www.aclweb.org/" target="_blank">Association for Computational Linguistics</a>
</p>
<!--
<p>
<a href="http://www.aclweb.org/"><img style="border-style: none" src="http://www.aclweb.org/templates/jt_simplicity_grey/images/header_logo.png" /></a>
</p>
-->
