<br>
<br>
<h3>French Newspaper Corpus</h3>
<h4>Part 1 - AFP 1994 and 1996</h4>
<p>
  Developed by <a href='http://www.hf.uio.no/tekstlab/'>The Text Laboratory</a>. 
</p>
<p>
  <a href="http://www.hf.uio.no/tekstlab">
    <img style="border-style: none" src="html/img/logo.png" />
  </a>
</p>
<p>
  Contains texts from the
  <a href="http://www.ldc.upenn.edu/" target="_blank">
    Linguistic Data Consortium
  </a>.
</p>
<p>
  <a href="http://www.ldc.upenn.edu/">
    <img style="border-style: none"
         src="http://www.ldc.upenn.edu/Shared/Graphics/logo.gif" />
  </a>
</p>
