<input type="hidden" name="phrase_0_corpus" value="HULA"></input>
<table>
<tr>
	 <td valign="top"><script language="javascript">writeWidgetDoubleTable('title','tittel', 'hidden')</script></td>
	 <td valign="top"><script language="javascript">writeWidgetDoubleTable('tid','tittel-id', 'hidden')</script></td>
 </tr>
 <tr>
	 <td valign="top"><script language="javascript">writeWidgetDoubleTable('author','forfatter', 'hidden')</script></td>
	 <td valign="top"><script language="javascript">writeWidgetDoubleTable('startyear','fra år', 'hidden')</script></td>
	 <td valign="top"><script language="javascript">writeWidgetDoubleTable('endyear','til år', 'hidden')</script></td>
 </tr>
 </table>

