<div style="position: relative; left: -180px; top: 20px;background:#fff;">
<table>
<tr>
<!-- <td style='border-width:2px;border-style:outset;background:#cde;' valign="center" width="130px"> -->
<td  width="130px">
<span style="font-family:gothic century;font-variant:small-caps;font-weight:bold;font-size:1.4em;cursor:pointer;" onclick="document.location='http://www.hf.uio.no/iln/om/organisasjon/tekstlab/prosjekter/ruija/ruija.html';">The&nbsp;Ruija&nbsp;Corpus</span><br />
<!-- <span style="font-family:gothic century;font-variant:small-caps;font-weight:light;font-size:1.1em;">Et talespråkskorpus fra kvensk- og finskspråklige områder</span> -->
</td>
<td>
</td>
</tr>
<tr>
<td>
<img src="http://www.tekstlab.uio.no/glossa/html/img/ruija1-bittelite.jpg" width="130px" alt="Picture by Vilfred Ingil&aelig;" title="Picture by Vilfred Ingil&aelig;" style="border: 2px solid #888" />
</td>
</tr>
</table>
<span style="font-family:gothic century;font-variant:small-caps;font-weight:light;font-size:1.1em;"><a target="_blank" href="http://omilia.uio.no/ruija/">Transcriptions</a>&nbsp;&nbsp;<a target="_blank" href="http://www.hf.uio.no/iln/english/about/organization/text-laboratory/projects/ruija/ruija.html">Info</a></span>
</div>

