<input type="hidden" name="meta_values_active::LEGEPASIENTauthor.active" value="y" />
<input type="hidden" name="meta_mode_active" value="LIKE" />
<table width="100%" border="0">
  <tr>
    <td width="20%">Informant:</td>
    <td valign="top" width="30%">
      <script language="javascript">writeWidgetDoubleTable('persontype','type informant','hidden')</script>
    </td>
    <td valign="top">
      <script language="javascript">writeWidgetDoubleTable('tid','informant id','hidden')</script>
    </td>
  </tr>
</table>
<hr />
<table width="100%" border="0">
  <tr>
    <td width="20%">Leger:</td>
    <td valign="top">
      <script language="javascript">writeWidgetDoubleTable('drlang','språk','hidden')</script>
    </td>
    <td valign="top">
      <script language="javascript">writeWidgetRadio('drsex','kjønn', 'hidden')</script>
    </td>
    <td valign="top">
      <script language="javascript">writeWidgetDoubleTable('drage','alder', 'hidden')</script>
    </td>
   </tr>
</table>
<hr />
<table width="100%" border="0">
  <tr>
    <td width="20%">Pasienter:</td>
    <td valign="top">
      <script language="javascript">writeWidgetDoubleTable('plang','språk','hidden')</script>
    </td>
    <td valign="top">
      <script language="javascript">writeWidgetRadio('psex','kjønn', 'hidden')</script>
    </td>
    <td valign="top">
      <script language="javascript">writeWidgetDoubleTable('page','alder', 'hidden')</script>
    </td>
   </tr>
</table>
<hr />
<table width="100%" border="0">
  <tr>
    <td width="20%">Konsultasjon:</td>
    <td valign="top" width="30%">
      <script language="javascript">writeWidgetDoubleTable('constype','type konsultasjon','hidden')</script>
    </td>
    <td valign="top" width="30%">
      <script language="javascript">writeWidgetRadio('relativespresent','pårørende til stede?','hidden')</script>
    </td>
    <td></td>
  </tr>
</table>
<hr />
<table>
  <tr>
  </tr>
</table>
<!--
<div id="layer1">
  <span id="close"><a href="javascript:setVisible('layer1')" style="text-decoration: none"><strong>close</strong></a></span>
   <iframe frameborder="0" width="100%" height="90%" id="phonetics"></iframe>
</div>
-->
