<input type="hidden" name="phrase_0_corpus" value="MME"></input>
<table>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('artist','artist','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('genre','sjanger','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('newspaper','avis', 'hidden')</script></td>
 </tr>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('specification','spesifikasjon', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('year','år', 'hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('title','tittel', 'hidden')</script> </td>
 </tr>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('typegim','type GIM', 'hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('typelistening','type lytting', 'hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('program','program', 'hidden')</script> </td>
 </tr>
</table>
