<input type="hidden" name="phrase_0_corpus" value="MUSIKK"></input>
<table>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('artist','artist','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('genre','sjanger','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('newspaper','avis', 'hidden')</script></td>
 </tr>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('newspapertype','avistype', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('header','overskrift', 'hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('misc','diverse', 'hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('tid','tittel-id', 'hidden')</script> </td>
 </tr>
</table>
