<div style="position: relative; left: 10px; top: 145px;background:#fff;">
  <table cellspacing="1" border="0" width="300px">
    <tr>
      <td valign="center" width="80px">
        <a href="http://norm.skrivesenteret.no/"><img style='border-style: none'
             src="http://norm.skrivesenteret.no/wp-content/uploads/2012/02/bl%C3%A5-logo1-300x66.jpg" /></a>
      </td>
      <td>
        <strong><strong>
      </td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>
  </table>
</div>
