<input type="hidden" name="meta_mode_active" value="LIKE" />
<table>
<tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('school', 'skole', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('level', 'trinn', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('student', 'elevnummer', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetCheck('sex', 'kjonn', 'hidden')</script></td>
</tr>
<tr>
  <td valign="top"><script language="javascript">writeWidgetCheck('nativelanguage', 'morsmål', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('assignmenttype', 'oppgavetype', 'hidden')</script></td>
</tr>
</table>
