<div style="position: relative; left: -180px; top: 20px;background:#fff;">
  <table>
    <tr>
      <td valign="center" width="80px">
        <a target="_blank" href="http://www.tekstlab.uio.no/nota/oslo/">
          <img style='border-style: none'
               src='http://www.tekstlab.uio.no/nota/img/nota_63x42.png' />
        </a>
      </td>
      <td>
        <strong>Norwegian speech corpus<br />Oslodelen<strong>
      </td>
    </tr>
    <tr>
      <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
      <td valign="center">
        Developed at 
      </td>
      <td align="left">
        <a target="_blank" href='http://www.hf.uio.no/tekstlab'>
          <img style='border-style: none' src='img/logo.png' />
        </a>
      </td>
    </tr>
  </table>
</div>
<div style="position: relative; left: -220px; top: 32px">
<ul>
  <li><a target="_blank" href="transcriptions/nota">Transcriptions</a></li>
  <li><a target="_blank" href="http://www.tekstlab.uio.no/nota/scandiasyn/help/">News: Search Interface Documentation</a></li>
</ul>
</div>