<div style="position: relative; left: 10px; top: 145px;background:#fff;">
  <table cellspacing="1" border="0" width="300px">
    <tr>
      <td valign="center" width="80px">
        <a target="_blank" href="http://www.tekstlab.uio.no/nota/oslo/">
          <img style='border-style: none'
               src='http://www.tekstlab.uio.no/nota/img/nota_63x42.png' />
        </a>
      </td>
      <td>
        <strong>Norwegian speech corpus<br />Oslodelen<strong>
      </td>
    </tr>
    <tr>
      <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
      <td valign="center">
        Developed at 
      </td>
      <td align="left">
        <a target="_blank" href='http://www.hf.uio.no/tekstlab'>
          <img style='border-style: none' src='img/logo.png' />
        </a>
      </td>
    </tr>
  </table>
</div>
