
<input type="hidden" name="meta_values_active::NOTAauthor.active" value="y" />
<input type="hidden" name="meta_mode_active" value="LIKE" />
<table>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('tid','informant','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetRadio('rep','representativ utvalg','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('genre','situasjon','hidden')</script> </td>
 </tr>
</table>
<hr>
<table width="100%">
 <tr>
  <td valign="top" width="33%"><script language="javascript">writeWidgetDoubleTable('bredreg','oppvokst','hidden')</script> </td>
  <td valign="top" width="33%"><script language="javascript">writeWidgetDoubleTable('abodereg','bosted','hidden')</script> </td>
  <td valign="top" width="33%"><script language="javascript">writeWidgetDoubleTable('longestreg','bodd lengst', 'hidden')</script></td>
 </tr>
  <tr>
  <td valign="top" width="33%"><script language="javascript">writeWidgetDoubleTable('bred','detaljert','hidden')</script> </td>
  <td valign="top" width="33%"><script language="javascript">writeWidgetDoubleTable('abode','detaljert','hidden')</script> </td>
  <td valign="top" width="33%"><script language="javascript">writeWidgetDoubleTable('longest','detaljert', 'hidden')</script></td>
 </tr>
</table>
<table>
<hr>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetCheck('agegroup','aldersgruppe', 'hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetCheck('sex','kjønn', 'hidden')</script> </td>
 </tr>
</table>
<table>
<hr>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetCheck('edu','utdannelse', 'hidden')</script>    </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('pro','yrke', 'hidden')</script></td>
</tr>
</table>
<table>


 <tr>



 </tr>

 <tr>

 </tr>
</table>
