<br>
<br>

<h3>The Oslo Multilingual Corpus</h3>

Developed by
<a href='http://www.hf.uio.no/forskningsprosjekter/sprik/english/index.html'>
  The Sprik project
</a>
,

<br>
in cooperation with
<a href='http://www.hf.uio.no/tekstlab/'>
  The Text Laboratory
</a>.

<br>
<br>

<a href='http://www.hf.uio.no/forskningsprosjekter/sprik/english/index.html'>
  <img style='border-style: none'
       src='http://www.hf.uio.no/iln/tjenester/sprak/korpus/flersprakligekorpus/omc/languages_Max_Estes-lite.jpg' />
</a>

<br>
<br>

<a href='http://www.hf.uio.no/tekstlab'>
  <img style='border-style: none' src='img/logo.png' />
</a>

<br>
<br>

<a href='http://www.hf.uio.no/iln'>
  <img style='border-style: none' src='img/logo-uio.png' />
</a>
