<input type="hidden" name="phrase_0_corpus" value="POLITIKK"></input>
<script language="javascript">writeWidgetDoubleTable('meta','meta','hidden')</script> 

<table>
 <tr>
 <td valign="top"><script language="javascript">writeWidgetDoubleTable('tid','tittel-id', 'hidden')</script></td>
 <td valign="top"><script language="javascript">writeWidgetDoubleTable('party','parti', 'hidden')</script></td>
 <td valign="top"><script language="javascript">writeWidgetDoubleTable('period','periode', 'hidden')</script></td>
 </tr>
 </table>

