<br>
<br>
<h3>The RuN Corpus</h3>
Developed by <a href='http://www.hf.uio.no/ilos/forskning/forskningsprosjekter/run/'>The RuN project</a>,<br> in cooperation with <a href='http://www.hf.uio.no/tekstlab/'>The Text Laboratory</a>.
<br><br>
<a href='http://www.hf.uio.no/ilos/forskning/forskningsprosjekter/run/'><img width="100" style='border-style: none' src='http://www.hf.uio.no/ilos/english/research/projects/run/photos/run_logo2.jpg' /></a>
<br><br>
 <?php echo "<a href='http://www.hf.uio.no/tekstlab'><img style='border-style: none' src='" . $htmlRoot . "html/img/logo.png' /></a>"; ?> 

<br><br>

 <?php echo "<a href='http://www.hf.uio.no/iln'><img style='border-style: none' src='" . $htmlRoot . "html/img/logo-uio.png' /></a>"; ?> 
