<table>
  <tr>
    <td valign="top">
      <input type="hidden" name="meta_values_active::SCANDIASYNauthor.active" value="y" />
      <input type="hidden" name="meta_mode_active" value="LIKE" />
      <script language="javascript">writeWidgetDoubleTable('tid','informant','hidden')</script>
    </td>
  </tr>
</table>
<hr />
<table width="100%" border="0">
  <tr>
    <td valign="top" width="20%">
      <script language="javascript">writeWidgetDoubleTable('country','country','hidden')</script>
    </td>
    <td valign="top" width="20%">
      <script language="javascript">writeWidgetDoubleTable('region','region','hidden')</script>
    </td>
        <td valign="top" width="20%">
      <script language="javascript">writeWidgetDoubleTable('area','area','hidden')</script>
    </td>
    <td valign="top" width="20%">
      <script language="javascript">writeWidgetDoubleTable('place','place','hidden')</script>
    </td>
   </tr>
</table>
<table>
<hr />
<table>
  <tr>
    <td valign="top">
      <script language="javascript">writeWidgetRadio('agegroup','agegroup', 'hidden')</script>
    </td>
    <td valign="top">
      <script language="javascript">writeWidgetRadio('sex','sex', 'hidden')</script>
    </td>
    <td valign="top">
      <script language="javascript">writeWidgetDoubleTable('rec','rec (year)', 'hidden')</script>
    </td>

    <td valign="top">
      <script language="javascript">writeWidgetDoubleTable('genre','genre', 'hidden')</script>
    </td>

  </tr>
</table>
<!--
<div id="layer1">
  <span id="close"><a href="javascript:setVisible('layer1')" style="text-decoration: none"><strong>close</strong></a></span>
   <iframe frameborder="0" width="100%" height="90%" id="phonetics"></iframe>
</div>
-->