<div style="position: relative; left: 10px; top: 145px;background:#fff;">
  <table cellspacing="1" border="0" width="300px">
    <tr>
      <td valign="center" width="80px">
        <img style='border-style: none'
             src='http://www.tekstlab.uio.no/skriv/img/skriv-logo.jpg' />
      </td>
      <td>
        <strong><strong>
      </td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>
    <tr>
      <td valign="center">
        Developed at
      </td>
      <td align="left">
        <a target="_blank" href='http://www.hf.uio.no/tekstlab'>
          <img style='border-style: none' src='img/logo.png' />
        </a>
      </td>
    </tr>
  </table>
</div>
