<input type="hidden" name="meta_mode_active" value="LIKE" />
<table>
<tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('student', 'elevnummer', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('nativelanguage', 'morsmål', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetCheck('school', 'skolekode', 'hidden')</script></td>
</tr>
<tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('specialisation', 'linjekode', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('worksheet', 'oppgavesett', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('assignmentpart', 'oppgavedel', 'hidden')</script></td>
</tr>
</table>
