<div style="position: relative; left: 10px; top: 145px;background:#fff;">
  <table cellspacing="1" border="0" width="300px">
    <tr>
      <td valign="center" width="80px">
        <img style='border-style: none'
             src='http://www.tekstlab.uio.no/skriv/img/skriv-logo.jpg' />
      </td>
      <td>
        <strong><strong>
      </td>
    </tr>
    <tr><td colspan="2">&nbsp;</td></tr>
  </table>
</div>
