
<table>
<hr>
 <tr>
  <td valign="top">
      <input type="hidden" name="meta_values_active::TAUSauthor.active" value="Y" />
      <input type="hidden" name="meta_mode_active" value="LIKE" />
      <script language="javascript">writeWidgetDoubleTable('tid','informant','hidden')</script>
  </td>
<!--  <td valign="top"><script language="javascript">writeWidgetFromTo('age','age', 'hidden')</script>    </td>-->
  <td valign="top"><script language="javascript">writeWidgetCheck('sex','sex', 'hidden')</script> </td>
 </tr>
</table>
<hr />
<table>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('abode','abode','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('pro','occupation', 'hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetCheck('edu','education', 'hidden')</script>    </td>
 </tr>
</table>