<div style="position: absolute; left: 500px; top: 40px;background:#fff;">
  <table>
    <tr>
      <td valign="center" width="80px">
        <a href = 'http://www.tekstlab.uio.no/nota/taus/index.html' >
          <img style='border-style: none'
               src='http://www.tekstlab.uio.no/nota/img/taus-btransp.png' />
        </a>
      </td>
      <td>
        <strong>TAUS - Talemålsundersøkelsen i Oslo<strong>
      </td>
    </tr>
    <tr>
      <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
      <td valign="center">
        Developed by
      </td>
      <td align="left">
        <a href='http://www.hf.uio.no/tekstlab'>
          <img style='border-style: none'
               src='img/logo.png' />
        </a>
      </td>
    </tr>
  </table>
</div>
