<table>
  <tr>
    <td valign="top">
      <input type="hidden" name="meta_values_active::TIGRINYAauthor.active" value="y" />
      <input type="hidden" name="meta_mode_active" value="LIKE" />
      <script language="javascript">writeWidgetDoubleTable('tid','informant','hidden')</script>
    </td>
    <td valign="top">
<!--      <script language="javascript">writeWidgetDoubleTable('language','language','hidden')</script> -->
    </td>
  </tr>
</table>
<hr />
<table width="100%" border="0">
  <tr>
    <td valign="top" width="20%">
<!--      <script language="javascript">writeWidgetDoubleTable('kvenoplace','place','hidden')</script> -->
    </td>
   </tr>
</table>
<table>
<hr />
<table>
  <tr>
    <td valign="top">
      <script language="javascript">writeWidgetRadio('sex','sex', 'hidden')</script>
    </td>
    <td valign="top">
<!--      <script language="javascript">writeWidgetDoubleTable('rec','rec (year)', 'hidden')</script> -->
    </td>
    <td valign="top">
<!--      <script language="javascript">writeWidgetDoubleTable('source','source', 'hidden')</script> -->
    </td>
  </tr>
</table> 