








<table>


 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('tid','informant','hidden')</script></td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('genre','situasjon', 'hidden')</script></td>

 </tr>
</table>
<hr>
<table>

 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('place','sted','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('agegroup','agegroup','hidden')</script> </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('raised','oppvokst', 'hidden')</script></td>

 </tr>
</table>
<table>
<hr>
 <tr>

  <td valign="top"><script language="javascript">writeWidgetDoubleTable('parents','foreldre', 'hidden')</script></td>
   <td valign="top"><script language="javascript">writeWidgetDoubleTable('sex','kj&oslash;nn', 'hidden')</script>    </td>
 </tr>
</table>
<table>
<hr>
 <tr>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('lang','spr&aring;k', 'hidden')</script>    </td>
  <td valign="top"><script language="javascript">writeWidgetDoubleTable('langs','antall spr&aring;k', 'hidden')</script>    </td>
 </tr>
</table>
<table>


 <tr>



 </tr>

 <tr>

 </tr>
</table>
